version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-database
    restart: always
    env_file:
      - .env.database
    networks:
      - server_network
    ports:
      - "5432:5432"

  nest-app:
    container_name: nest-js-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - server_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  server_network:
    driver: bridge